name: NPM Global
description: Installs required global NPM package.
author: Lendi Platform Team
requirements:
  - bash
  - node
configuration:
  properties:
    registry:
      type: string
    token:
      type: string
    env:
      type: string
    file:
      type: string
    package:
      type: string
    authtype:
      type: string
